[[target]]
name = "PastaCranker"
assets = [
    "res/crank/crank0.png",
    "res/crank/crank1.png",
    "res/crank/crank2.png",
    "res/crank/crank3.png",
    "res/crank/crank4.png",
    "res/crank/crank5.png",
    "res/crank/crank6.png",
    "res/crank/crank7.png",
    "res/crank/crank8.png",
    "res/crank/crank9.png",
    "res/crank/crank10.png",
    "res/crank/crank11.png",
    "res/crank/crank12.png",
    "res/crank/crank13.png",
    "res/machine_body.png",
    "res/roller_dough/roller_dough0.png",
    "res/roller_dough/roller_dough1.png",
    "res/roller_dough/roller_dough2.png",
    "res/roller_dough/roller_dough3.png",
    "res/roller_dough/roller_dough_bottom0.png",
    "res/roller_dough/roller_dough_bottom1.png",
    "res/roller_dough/roller_dough_bottom2.png",
    "res/roller_dough/roller_dough_bottom3.png",
    "res/doughball.png",
    "res/bottom_bar.png",
    "res/menu_indicator_left.png",
    "res/menu_indicator_right.png",
    "res/bar_background.png",
    "res/flour_pile.png",
    "res/a_button.png",
    "res/a_button_pressed.png",
    "res/menu_background.png",
    "res/menu_item_background0.png",
    "res/menu_item_background1.png",
    "res/menu_item_background2.png",
    "res/diamond.png",
    "res/coin.png",
    "res/audio/75235__creek23__cha-ching.wav",
    "res/audio/611800__metalfortress__confirm.wav",
    "res/audio/220187__gameaudio__loosedeny-casual-1.wav",
    "res/audio/330997__rudmer_rotteveel__stick-hitting-a-dreadlock-small-thud.wav",
    "res/crank-gearbox.png",
    "res/gran.png",
    "res/info_overlay.png"
]